messages:
  accepteeMsg: 'Accepted request.'
  denyeeMsg: 'Denied request.'
  accepterMsg: 'Request to teleport accepted.'
  denierMsg: 'Request to teleport denied.'
  fromMsg: '%p would like to %t'
  tpToThemMsg: 'teleport to you'
  tpThemToYouMsg: 'teleport you to them'
  acceptDenyPrompt: 'To accept this, type %a. To deny, type %d'
  playerHasPendingReq: 'That player already has a pending request!'
  requestSent: 'Request sent'
  playerNotFound: '§cPlayer %p not found'
  playerCommand: '§cThis command is only available in game to players'
  selfTp: '§cYou cannot to yourself'
  toggledMsg: '§c%p §7 is not accepting requests'
  backUsage: '§7Teleporting you to your previous location'
  noBackLocation: '§7No previous location'
  removeReq: '§7Requests removed'
  teleportation: '§7Teleportation'
  allowed: 'Allowed'
  disabled: 'Disabled'
  permissionDenied: 'permissionDenied'
settings:
  clearRequestsOnWorldChange: false
  useBukkitPerms: false
  requestTimeout: 30
