name: TeleConfirmLite
version: 2.0.6
main: com.ementalo.tcl.TeleConfirmLite
authors:
  - ementalo
commands:
  tpc:
    description: Request to teleport to the specified player.
    usage: /<command> <player>
  tpca:
    description: Accepts a teleport request.
    usage: /<command>
  tpchere:
    description: Request that the specified player teleport to you.
    usage: /<command> <player>
  tpcd:
    description: Reject a teleport request.
    usage: /<command>
  tpctoggle:
    description: Toggle telportation.
    usage: /<command>
  tpcclear:
    description: Removes a pending request.
    usage: /<command>
  tpcback:
    description: Returns you to your previous location
    usage: /<command>
      
  